issus in this script in unity 2019.3.0a5
in unity 2019.3.0a5 GameAnalytics have issus in GA_PostprocessBuild.cs 
messsage error : 
Assets/GameAnalytics/Editor/GA_PostprocessBuild.cs(21,25): error CS0619: 'PBXProject.GetUnityTargetName()' is obsolete: 'This function is deprecated. There are two targets now, call GetUnityMainTargetGuid() - for app or GetUnityFrameworkTargetGuid() - for source/plugins to get Guid instead of calling to TargetGuidByName(GetUnityTargetName()).'
- i try to fix it but if i change any think and save script gameanalytics.dll refuse and blocked unity